# vars/deploy_vars.yml — Model deployment variables

# Docker Image
docker_image: "achriki/edgeia-person-detector"
# image_tag is defined in the playbook (can be overridden via -e)

# Kubernetes
k8s_namespace: "default"
deployment_name: "person-detector"
container_name: "person-detector"
k8s_manifest_dir: "/home/achriki/k8s" # manifests folder in the Pi

# Rollout
rollout_timeout: 300 #  Pi 3B needs more time under memory pressure
rollout_poll_interval: 5 # seconds between each kubectl check

# Health check
health_check_port: 30080 # NodePort specified in service.yaml
health_check_path: "/health"
health_check_retries: 10
health_check_delay: 5 # seconds between each retry

# Kubeconfig paths
kubeconfig_path: "/home/achriki/.kube/config"
kubectl_bin: "/usr/local/bin/kubectl"